/* Generated by Yosys 0.65 (git sha1 b85cad634782fafac275e5f540c056bfacb2b5d2) */

(* top =  1  *)
(* src = "fsm_vending_machine.v:1.1-256.10" *)
module fsm_vending_machine(clk, reset, coin_5, coin_10, coin_25, req_item_a, req_item_b, dispense_a, dispense_b, insufficient_funds, change_returned, total_funds);
  (* src = "fsm_vending_machine.v:2.12-2.15" *)
  input clk;
  wire clk;
  (* src = "fsm_vending_machine.v:2.17-2.22" *)
  input reset;
  wire reset;
  (* src = "fsm_vending_machine.v:2.24-2.30" *)
  input coin_5;
  wire coin_5;
  (* src = "fsm_vending_machine.v:2.32-2.39" *)
  input coin_10;
  wire coin_10;
  (* src = "fsm_vending_machine.v:2.41-2.48" *)
  input coin_25;
  wire coin_25;
  (* src = "fsm_vending_machine.v:2.50-2.60" *)
  input req_item_a;
  wire req_item_a;
  (* src = "fsm_vending_machine.v:2.62-2.72" *)
  input req_item_b;
  wire req_item_b;
  (* src = "fsm_vending_machine.v:4.16-4.26" *)
  output dispense_a;
  wire dispense_a;
  (* src = "fsm_vending_machine.v:4.28-4.38" *)
  output dispense_b;
  wire dispense_b;
  (* src = "fsm_vending_machine.v:4.40-4.58" *)
  output insufficient_funds;
  wire insufficient_funds;
  (* src = "fsm_vending_machine.v:6.22-6.37" *)
  output [7:0] change_returned;
  reg [7:0] change_returned;
  (* src = "fsm_vending_machine.v:8.22-8.33" *)
  output [7:0] total_funds;
  reg [7:0] total_funds;
  (* src = "fsm_vending_machine.v:226.5-254.8" *)
  wire [7:0] _000_;
  (* src = "fsm_vending_machine.v:42.5-67.8" *)
  wire [7:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  (* src = "fsm_vending_machine.v:31.9-31.25" *)
  wire ctrl_clear_funds;
  (* onehot = 32'd1 *)
  reg [6:0] current_state;
  assign _048_ = ~total_funds[1];
  assign _049_ = ~(current_state[1] | current_state[5]);
  assign ctrl_clear_funds = ~_049_;
  assign _050_ = ~(current_state[4] & coin_10);
  assign _051_ = coin_25 | _050_;
  assign _052_ = total_funds[1] & total_funds[0];
  assign _053_ = total_funds[2] | _052_;
  assign _054_ = total_funds[3] & _053_;
  assign _055_ = ~(total_funds[4] & _054_);
  assign _056_ = _051_ & _055_;
  assign _057_ = ~(current_state[4] & coin_25);
  assign _058_ = total_funds[2] & total_funds[1];
  assign _059_ = ~_058_;
  assign _060_ = total_funds[3] | _058_;
  assign _061_ = total_funds[4] & _060_;
  assign _062_ = _051_ | _061_;
  assign _063_ = _057_ & _062_;
  assign _064_ = _056_ | ~(_063_);
  assign _065_ = ~(total_funds[0] & _058_);
  assign _066_ = ~(total_funds[4] | total_funds[3]);
  assign _067_ = _065_ & _066_;
  assign _068_ = _057_ | _067_;
  assign _069_ = ~(_064_ & _068_);
  assign _070_ = total_funds[5] & _069_;
  assign _071_ = ~(total_funds[6] & _070_);
  assign _072_ = total_funds[6] | _070_;
  assign _073_ = _049_ & _072_;
  assign _001_[6] = _071_ & _073_;
  assign _074_ = total_funds[5] | _069_;
  assign _075_ = _049_ & _074_;
  assign _001_[5] = _075_ & ~(_070_);
  assign _076_ = ~(_054_ & _056_);
  assign _077_ = _057_ & ~(_060_);
  assign _078_ = _063_ | _077_;
  assign _079_ = ~(_076_ & _078_);
  assign _080_ = ~(_068_ & _079_);
  assign _081_ = _057_ | ~(_065_);
  assign _082_ = total_funds[3] | _081_;
  assign _083_ = total_funds[4] & _082_;
  assign _084_ = ~(_064_ & _083_);
  assign _085_ = ~(_080_ & _084_);
  assign _001_[4] = _049_ & _085_;
  assign _086_ = _059_ & ~(_051_);
  assign _087_ = _051_ ? _053_ : _059_;
  assign _088_ = _057_ ? _087_ : _065_;
  assign _089_ = ~(total_funds[3] & _088_);
  assign _090_ = total_funds[3] | _088_;
  assign _091_ = _049_ & _090_;
  assign _001_[3] = _089_ & _091_;
  assign _092_ = ~(_053_ & _065_);
  assign _093_ = ~(_051_ & _092_);
  assign _094_ = total_funds[2] | total_funds[1];
  assign _095_ = ~(_086_ & _094_);
  assign _011_ = _093_ & _095_;
  assign _012_ = ~(_057_ & _011_);
  assign _013_ = _057_ | ~(_092_);
  assign _014_ = _049_ & _013_;
  assign _001_[2] = _012_ & _014_;
  assign _015_ = total_funds[1] ^ total_funds[0];
  assign _016_ = _051_ ? _015_ : _048_;
  assign _001_[1] = _049_ & _016_;
  assign _017_ = _049_ & ~(total_funds[0]);
  assign _001_[0] = _051_ & _017_;
  assign _018_ = _066_ | ~(total_funds[5]);
  assign _019_ = ~_018_;
  assign _020_ = total_funds[3] & ~(_065_);
  assign _021_ = total_funds[4] | _020_;
  assign _022_ = total_funds[5] | _021_;
  assign _023_ = current_state[1] ? _022_ : _019_;
  assign _024_ = total_funds[6] | _023_;
  assign _000_[6] = ~(total_funds[6] ^ _023_);
  assign _025_ = current_state[1] ? _021_ : _066_;
  assign _000_[5] = ~(total_funds[5] ^ _025_);
  assign _026_ = current_state[1] & _065_;
  assign _027_ = total_funds[3] & ~(_026_);
  assign _000_[4] = ~(total_funds[4] ^ _027_);
  assign _000_[3] = ~(total_funds[3] ^ _026_);
  assign _028_ = current_state[1] | ~(total_funds[2]);
  assign _029_ = ~(_053_ & _026_);
  assign _000_[2] = ~(_028_ & _029_);
  assign _000_[1] = current_state[1] ? _015_ : total_funds[1];
  assign _000_[0] = total_funds[0] ^ current_state[1];
  assign _030_ = coin_10 | coin_25;
  assign _031_ = ~(coin_5 | _030_);
  assign _032_ = coin_5 | _030_;
  assign _033_ = ~(current_state[4] & _032_);
  assign _009_ = ~(_049_ & _033_);
  assign _034_ = ctrl_clear_funds | _051_;
  assign _010_ = _009_ & _034_;
  assign _004_ = current_state[0] & _032_;
  assign _035_ = ~(total_funds[7] | total_funds[6]);
  assign _036_ = ~(_018_ & _035_);
  assign _005_ = current_state[6] & _036_;
  assign _037_ = current_state[6] & ~(_036_);
  assign _038_ = _022_ | ~(_035_);
  assign _039_ = current_state[2] & ~(_038_);
  assign _008_ = _037_ | _039_;
  assign _040_ = req_item_a & current_state[0];
  assign _003_ = _031_ & _040_;
  assign _002_ = current_state[2] & _038_;
  assign _041_ = current_state[0] & ~(req_item_a);
  assign _042_ = _041_ & ~(req_item_b);
  assign _043_ = ~(_031_ & _042_);
  assign _044_ = ~(current_state[3] | current_state[4]);
  assign _045_ = _049_ & _044_;
  assign _007_ = ~(_043_ & _045_);
  assign _046_ = req_item_b & _041_;
  assign _006_ = _031_ & _046_;
  assign _000_[7] = ~(total_funds[7] ^ _024_);
  assign _047_ = ~(total_funds[7] ^ _071_);
  assign _001_[7] = _049_ & _047_;
  (* src = "fsm_vending_machine.v:42.5-67.8" *)
  always @(posedge clk, posedge reset)
    if (reset) total_funds[1] <= 1'h0;
    else if (_009_) total_funds[1] <= _001_[1];
  (* src = "fsm_vending_machine.v:42.5-67.8" *)
  always @(posedge clk, posedge reset)
    if (reset) total_funds[2] <= 1'h0;
    else if (_009_) total_funds[2] <= _001_[2];
  (* src = "fsm_vending_machine.v:42.5-67.8" *)
  always @(posedge clk, posedge reset)
    if (reset) total_funds[3] <= 1'h0;
    else if (_009_) total_funds[3] <= _001_[3];
  (* src = "fsm_vending_machine.v:42.5-67.8" *)
  always @(posedge clk, posedge reset)
    if (reset) total_funds[4] <= 1'h0;
    else if (_009_) total_funds[4] <= _001_[4];
  (* src = "fsm_vending_machine.v:42.5-67.8" *)
  always @(posedge clk, posedge reset)
    if (reset) total_funds[5] <= 1'h0;
    else if (_009_) total_funds[5] <= _001_[5];
  (* src = "fsm_vending_machine.v:42.5-67.8" *)
  always @(posedge clk, posedge reset)
    if (reset) total_funds[6] <= 1'h0;
    else if (_009_) total_funds[6] <= _001_[6];
  (* src = "fsm_vending_machine.v:42.5-67.8" *)
  always @(posedge clk, posedge reset)
    if (reset) total_funds[7] <= 1'h0;
    else if (_009_) total_funds[7] <= _001_[7];
  (* src = "fsm_vending_machine.v:42.5-67.8" *)
  always @(posedge clk, posedge reset)
    if (reset) total_funds[0] <= 1'h0;
    else if (_010_) total_funds[0] <= _001_[0];
  (* src = "fsm_vending_machine.v:226.5-254.8" *)
  always @(posedge clk, posedge reset)
    if (reset) change_returned[0] <= 1'h0;
    else if (ctrl_clear_funds) change_returned[0] <= _000_[0];
  (* src = "fsm_vending_machine.v:226.5-254.8" *)
  always @(posedge clk, posedge reset)
    if (reset) change_returned[1] <= 1'h0;
    else if (ctrl_clear_funds) change_returned[1] <= _000_[1];
  (* src = "fsm_vending_machine.v:226.5-254.8" *)
  always @(posedge clk, posedge reset)
    if (reset) change_returned[2] <= 1'h0;
    else if (ctrl_clear_funds) change_returned[2] <= _000_[2];
  (* src = "fsm_vending_machine.v:226.5-254.8" *)
  always @(posedge clk, posedge reset)
    if (reset) change_returned[3] <= 1'h0;
    else if (ctrl_clear_funds) change_returned[3] <= _000_[3];
  (* src = "fsm_vending_machine.v:226.5-254.8" *)
  always @(posedge clk, posedge reset)
    if (reset) change_returned[4] <= 1'h0;
    else if (ctrl_clear_funds) change_returned[4] <= _000_[4];
  (* src = "fsm_vending_machine.v:226.5-254.8" *)
  always @(posedge clk, posedge reset)
    if (reset) change_returned[5] <= 1'h0;
    else if (ctrl_clear_funds) change_returned[5] <= _000_[5];
  (* src = "fsm_vending_machine.v:226.5-254.8" *)
  always @(posedge clk, posedge reset)
    if (reset) change_returned[6] <= 1'h0;
    else if (ctrl_clear_funds) change_returned[6] <= _000_[6];
  (* src = "fsm_vending_machine.v:226.5-254.8" *)
  always @(posedge clk, posedge reset)
    if (reset) change_returned[7] <= 1'h0;
    else if (ctrl_clear_funds) change_returned[7] <= _000_[7];
  always @(posedge clk, posedge reset)
    if (reset) current_state[0] <= 1'h1;
    else current_state[0] <= _007_;
  always @(posedge clk, posedge reset)
    if (reset) current_state[1] <= 1'h0;
    else current_state[1] <= _002_;
  always @(posedge clk, posedge reset)
    if (reset) current_state[2] <= 1'h0;
    else current_state[2] <= _003_;
  always @(posedge clk, posedge reset)
    if (reset) current_state[3] <= 1'h0;
    else current_state[3] <= _008_;
  always @(posedge clk, posedge reset)
    if (reset) current_state[4] <= 1'h0;
    else current_state[4] <= _004_;
  always @(posedge clk, posedge reset)
    if (reset) current_state[5] <= 1'h0;
    else current_state[5] <= _005_;
  always @(posedge clk, posedge reset)
    if (reset) current_state[6] <= 1'h0;
    else current_state[6] <= _006_;
  assign insufficient_funds = current_state[3];
  assign dispense_b = current_state[5];
  assign dispense_a = current_state[1];
endmodule
